// mobile/src/styles/appStyles.ts
import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../theme/themes';

export function getAppStyles(theme: ThemeColors, isDesktop: boolean) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.bg,
      width: '100%',
    },
    mainLayout: {
      flex: 1,
      backgroundColor: theme.bg,
      width: '100%',
      maxWidth: '100%',
      overflow: 'hidden',
      ...(Platform.OS === 'web' ? ({ height: '100vh', maxHeight: '100vh' } as any) : {}),
    },
    desktopLayout: {
      maxWidth: 960,
      width: '100%',
      marginHorizontal: 'auto' as any,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderColor: theme.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
    },
    topHeader: {
      backgroundColor: theme.headerBg,
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      width: '100%',
    },
    headerTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
      marginBottom: 8,
    },
    titleContainer: {
      flex: 1,
      marginRight: 6,
    },
    portalTitle: {
      color: theme.headerText,
      fontSize: 18,
      fontWeight: '800',
    },
    headerRightGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    headerButton: {
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 7,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    headerButtonText: {
      color: theme.textPrimary,
      fontSize: 11,
      fontWeight: '600',
    },
    notifStatusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: '#10B981',
      marginLeft: 2,
    },
    headerSubRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      flexWrap: 'wrap',
      gap: 8,
    },
    headerSubLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    examTag: {
      backgroundColor: theme.primary,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      maxWidth: '65%',
    },
    examTagText: {
      color: theme.primaryText,
      fontWeight: '800',
      fontSize: 10,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    countdownText: {
      color: theme.textSecondary,
      fontSize: 11,
      fontWeight: '600',
    },
    userAuthBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
    },
    userAuthBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.primary,
    },

    // --- Merge Local Banner ---
    mergeBanner: {
      backgroundColor: 'rgba(59, 130, 246, 0.12)',
      borderWidth: 1,
      borderColor: theme.primary,
      marginHorizontal: 12,
      marginTop: 8,
      padding: 10,
      borderRadius: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    mergeBannerTitle: {
      fontSize: 12,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    mergeBannerSub: {
      fontSize: 10,
      color: theme.textSecondary,
      marginTop: 2,
    },
    mergeActionBtn: {
      backgroundColor: theme.primary,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 6,
    },
    mergeActionBtnText: {
      color: theme.primaryText,
      fontSize: 11,
      fontWeight: '800',
    },

    // --- Metrics Card ---
    metricsContainer: {
      backgroundColor: theme.metricsBg,
      marginHorizontal: 12,
      marginTop: 10,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 8,
      flexDirection: 'row',
      justifyContent: 'space-around',
      borderWidth: 1,
      borderColor: theme.border,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
    },
    metricBox: {
      alignItems: 'center',
      flex: 1,
    },
    metricDivider: {
      width: 1,
      height: '75%',
      backgroundColor: theme.border,
      alignSelf: 'center',
    },
    metricVal: {
      fontSize: 14,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    metricLabel: {
      fontSize: 10,
      color: theme.textSecondary,
      fontWeight: '600',
      marginTop: 2,
    },

    // --- Categories Tracker ---
    categoryTrackerSection: {
      marginHorizontal: 12,
      marginTop: 12,
      marginBottom: 2,
    },
    categoryTrackerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 6,
    },
    categoryTrackerTitle: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    categoryTrackerAddBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
    },
    categoryTrackerAddText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.primary,
    },
    categoryRailScroll: {
      gap: 6,
      paddingVertical: 2,
      paddingRight: 10,
    },
    categoryPill: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.surface,
      borderRadius: 18,
      paddingHorizontal: 9,
      paddingVertical: 5,
      borderWidth: 1,
      borderColor: theme.border,
      gap: 5,
    },
    categoryPillActive: {
      borderColor: theme.primary,
      backgroundColor: theme.surfaceElevated,
    },
    categoryPillText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    categoryCountBadge: {
      paddingHorizontal: 5,
      paddingVertical: 1,
      borderRadius: 8,
      backgroundColor: theme.surfaceElevated,
    },
    categoryCountBadgeText: {
      fontSize: 9,
      fontWeight: '800',
      color: theme.textSecondary,
    },
    catDeletePillBtn: {
      paddingHorizontal: 4,
      paddingVertical: 2,
      marginLeft: 2,
      borderRadius: 8,
    },
    catDeletePillText: {
      fontSize: 10,
      fontWeight: '800',
      color: '#EF4444',
    },

    // --- Day Selector ---
    daySelectorWrapper: {
      backgroundColor: theme.surface,
      marginTop: 8,
      borderBottomWidth: 1,
      borderColor: theme.border,
    },
    dayScrollContent: {
      paddingHorizontal: 8,
      paddingVertical: 6,
      gap: 5,
    },
    dayTab: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 7,
      backgroundColor: theme.tabBg,
      alignItems: 'center',
      minWidth: 52,
      borderWidth: 1,
      borderColor: theme.border,
    },
    dayTabActive: {
      backgroundColor: theme.tabActiveBg,
      borderColor: theme.tabActiveBg,
    },
    dayTabShort: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.tabText,
    },
    dayTabShortActive: {
      color: theme.tabActiveText,
    },
    dayTabFull: {
      fontSize: 8,
      color: theme.textMuted,
      marginTop: 1,
    },
    dayTabFullActive: {
      color: theme.tabActiveText,
    },

    // --- Timetable Slots Stream ---
    streamContent: {
      padding: 12,
      paddingBottom: 95,
    },
    emptyCard: {
      padding: 24,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 16,
      backgroundColor: theme.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: theme.border,
    },
    emptyIcon: {
      fontSize: 36,
      marginBottom: 8,
    },
    emptyTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textPrimary,
      marginBottom: 4,
      textAlign: 'center',
    },
    emptySub: {
      fontSize: 11,
      color: theme.textSecondary,
      textAlign: 'center',
      maxWidth: 260,
      lineHeight: 16,
    },
    slotCard: {
      backgroundColor: theme.surface,
      borderRadius: 10,
      marginBottom: 10,
      flexDirection: 'row',
      borderWidth: 1,
      borderColor: theme.border,
      overflow: 'hidden',
    },
    slotCardCompleted: {
      opacity: 0.75,
      backgroundColor: theme.surfaceElevated,
    },
    slotTypeAccent: {
      width: 4,
    },
    slotBody: {
      flex: 1,
      padding: 10,
    },
    cardHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 6,
    },
    typeBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 5,
    },
    typeBadgeText: {
      fontSize: 10,
      fontWeight: '700',
    },
    timeSpanGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    timeSpanText: {
      fontSize: 10,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    deleteSlotBtn: {
      padding: 2,
    },
    deleteSlotText: {
      color: '#EF4444',
      fontSize: 12,
      fontWeight: '700',
    },
    subjectText: {
      fontSize: 14,
      fontWeight: '800',
      color: theme.textPrimary,
      marginBottom: 2,
    },
    topicText: {
      fontSize: 11,
      color: theme.textSecondary,
      marginBottom: 8,
      lineHeight: 15,
    },
    cardFooterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    qTargetBadge: {
      backgroundColor: theme.surfaceElevated,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: theme.border,
    },
    qTargetText: {
      fontSize: 10,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    actionBtnGroup: {
      flexDirection: 'row',
      gap: 5,
    },
    statusBtn: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 5,
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
    },
    completedActiveBtn: {
      backgroundColor: '#10B981',
      borderColor: '#10B981',
    },
    skippedActiveBtn: {
      backgroundColor: '#EF4444',
      borderColor: '#EF4444',
    },
    statusBtnText: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    statusBtnTextActive: {
      color: '#FFFFFF',
    },
    fabTrigger: {
      position: 'absolute',
      bottom: 16,
      right: 14,
      backgroundColor: theme.primary,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 24,
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
    fabIcon: {
      color: theme.primaryText,
      fontWeight: '700',
      fontSize: 12,
    },

    // --- Modals Base ---
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.75)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 12,
    },
    modalCard: {
      backgroundColor: theme.surface,
      borderRadius: 14,
      padding: 14,
      width: '94%',
      maxHeight: '90%',
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalHeading: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    modalSubheading: {
      fontSize: 11,
      color: theme.textSecondary,
      marginBottom: 10,
    },
    fieldLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textSecondary,
      marginBottom: 4,
      marginTop: 6,
    },
    categoryLabelRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 6,
      marginBottom: 4,
    },
    addCategoryLink: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.primary,
    },
    inlineCategoryBox: {
      backgroundColor: theme.surfaceElevated,
      borderRadius: 10,
      padding: 10,
      borderWidth: 1,
      borderColor: theme.primary,
      marginVertical: 6,
    },
    inlineCategoryHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    inlineCategoryTitle: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    inlineCategoryClose: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textSecondary,
      padding: 2,
    },
    textInput: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 7,
      padding: 8,
      fontSize: 12,
      color: theme.textPrimary,
      backgroundColor: theme.surfaceElevated,
    },
    typeSelectorRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 5,
      marginVertical: 4,
    },
    typeChoice: {
      paddingHorizontal: 9,
      paddingVertical: 6,
      borderRadius: 7,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceElevated,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    typeChoiceText: {
      fontSize: 11,
      fontWeight: '600',
    },

    // --- Digital Watch Controls ---
    dualWatchContainer: {
      flexDirection: isDesktop ? 'row' : 'column',
      gap: 8,
      marginVertical: 6,
    },
    watchCard: {
      flex: 1,
      backgroundColor: theme.surfaceElevated,
      borderRadius: 8,
      padding: 8,
      borderWidth: 1,
      borderColor: theme.border,
    },
    watchHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    watchHeaderTitle: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    watchBigDisplay: {
      backgroundColor: theme.surface,
      borderRadius: 6,
      paddingVertical: 6,
      paddingHorizontal: 4,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 4,
      marginBottom: 6,
    },
    watchDigitBlock: {
      alignItems: 'center',
    },
    watchBigDigit: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    watchColon: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.textSecondary,
    },
    watchStepperRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 4,
    },
    stepperCol: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.surface,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: theme.border,
      overflow: 'hidden',
    },
    stepperBtn: {
      paddingVertical: 4,
      paddingHorizontal: 6,
    },
    stepperBtnText: {
      fontSize: 13,
      fontWeight: '800',
      color: theme.primary,
    },
    stepperValText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textPrimary,
      minWidth: 22,
      textAlign: 'center',
    },
    ampmToggleBtn: {
      backgroundColor: theme.primary,
      paddingVertical: 5,
      paddingHorizontal: 8,
      borderRadius: 5,
    },
    ampmToggleText: {
      color: theme.primaryText,
      fontSize: 10,
      fontWeight: '800',
    },
    quickSlotsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 4,
      marginTop: 4,
      marginBottom: 4,
    },
    quickSlotChip: {
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 7,
      paddingVertical: 4,
      borderRadius: 10,
    },
    quickSlotChipText: {
      fontSize: 9,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    previewBanner: {
      padding: 6,
      borderRadius: 6,
      borderWidth: 1,
      marginVertical: 6,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    previewBannerValid: {
      backgroundColor: 'rgba(16, 185, 129, 0.1)',
      borderColor: 'rgba(16, 185, 129, 0.3)',
    },
    previewBannerInvalid: {
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      borderColor: 'rgba(239, 68, 68, 0.3)',
    },
    previewBannerText: {
      fontSize: 10,
      fontWeight: '700',
    },
    modalActionGroup: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
      marginTop: 10,
    },
    abortBtn: {
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    abortBtnText: {
      color: theme.textMuted,
      fontWeight: '600',
      fontSize: 12,
    },
    confirmBtn: {
      backgroundColor: theme.primary,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 7,
    },
    confirmBtnDisabled: {
      opacity: 0.5,
    },
    confirmBtnText: {
      color: theme.primaryText,
      fontWeight: '700',
      fontSize: 12,
    },

    // Category Creator Picker Assets
    emojiGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 5,
      marginVertical: 4,
    },
    emojiChoice: {
      width: 32,
      height: 32,
      borderRadius: 6,
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emojiChoiceActive: {
      borderColor: theme.primary,
      backgroundColor: theme.surface,
    },
    colorPaletteGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginVertical: 4,
    },
    colorBall: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    colorBallActive: {
      borderColor: '#FFFFFF',
      transform: [{ scale: 1.15 }],
    },

    // Theme Picker
    themeListRow: {
      gap: 6,
      marginVertical: 6,
    },
    themeOptionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 10,
      borderRadius: 8,
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
    },
    themeOptionBtnActive: {
      borderColor: theme.primary,
      backgroundColor: theme.surface,
    },
    themeOptionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    themeOptionTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textPrimary,
    },

    // --- Authentication Modal Styles ---
    authTabRow: {
      flexDirection: 'row',
      borderRadius: 8,
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 12,
      overflow: 'hidden',
    },
    authTab: {
      flex: 1,
      paddingVertical: 8,
      alignItems: 'center',
    },
    authTabActive: {
      backgroundColor: theme.primary,
    },
    authTabText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    authTabTextActive: {
      color: theme.primaryText,
    },

    // --- Notifications Center ---
    notifToggleCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: theme.surfaceElevated,
      padding: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      marginVertical: 4,
    },
    notifToggleTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    notifToggleSubtitle: {
      fontSize: 10,
      color: theme.textSecondary,
      marginTop: 2,
    },
    notifSwitchBtn: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
      backgroundColor: theme.border,
    },
    notifSwitchBtnActive: {
      backgroundColor: '#10B981',
    },
    notifSwitchText: {
      fontSize: 10,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    notifLeadPillsRow: {
      flexDirection: 'row',
      gap: 6,
      marginVertical: 6,
    },
    notifLeadPill: {
      flex: 1,
      paddingVertical: 6,
      borderRadius: 6,
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
    },
    notifLeadPillActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    notifLeadPillText: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    notifLeadPillTextActive: {
      color: theme.primaryText,
    },
    notifQueueList: {
      maxHeight: 180,
      marginVertical: 6,
      backgroundColor: theme.surfaceElevated,
      borderRadius: 8,
      padding: 6,
      borderWidth: 1,
      borderColor: theme.border,
    },
    notifQueueItem: {
      padding: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    notifQueueTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 2,
    },
    notifQueueTime: {
      fontSize: 10,
      fontWeight: '800',
      color: theme.primary,
    },
    notifQueueType: {
      fontSize: 9,
      fontWeight: '700',
      color: theme.textSecondary,
      textTransform: 'uppercase',
    },
    notifQueueMsg: {
      fontSize: 10,
      color: theme.textPrimary,
      lineHeight: 14,
    },
    testAlarmBtn: {
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.primary,
      paddingVertical: 7,
      borderRadius: 7,
      alignItems: 'center',
      marginVertical: 6,
    },
    testAlarmBtnText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.primary,
    },

    // --- Custom Modal Dialog ---
    customDialogOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.75)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 16,
      zIndex: 9999,
    },
    customDialogCard: {
      backgroundColor: theme.surface,
      borderRadius: 12,
      padding: 16,
      width: '100%',
      maxWidth: 340,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 10,
    },
    customDialogTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: theme.textPrimary,
      marginBottom: 4,
    },
    customDialogMessage: {
      fontSize: 12,
      color: theme.textSecondary,
      lineHeight: 16,
      marginBottom: 14,
    },
    customDialogBtnGroup: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
    },
    customDialogCancelBtn: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 7,
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
    },
    customDialogCancelText: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    customDialogConfirmBtn: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 7,
      backgroundColor: theme.primary,
    },
    customDialogDangerBtn: {
      backgroundColor: '#EF4444',
    },
    customDialogConfirmText: {
      fontSize: 11,
      fontWeight: '700',
      color: '#FFFFFF',
    },
  });
}