// mobile/src/styles/appStyles.ts
import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../theme/themes';

export function getAppStyles(theme: ThemeColors, isDesktop: boolean) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.headerBg,
    },
    mainLayout: {
      flex: 1,
      backgroundColor: theme.bg,
      ...(Platform.OS === 'web'
        ? { height: '100vh' as any, maxHeight: '100vh' as any }
        : {}),
    },
    desktopLayout: {
      maxWidth: 960,
      width: '100%',
      marginHorizontal: 'auto' as any,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderColor: theme.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
    },
    topHeader: {
      backgroundColor: theme.headerBg,
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 20,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    headerRightGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    badgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 6,
    },
    examTag: {
      backgroundColor: theme.primary,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
    },
    examTagText: {
      color: theme.primaryText,
      fontWeight: '800',
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    countdownText: {
      color: theme.textSecondary,
      fontSize: 12,
      fontWeight: '600',
    },
    portalTitle: {
      color: theme.headerText,
      fontSize: 22,
      fontWeight: '800',
    },
    headerButton: {
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    headerButtonText: {
      color: theme.textPrimary,
      fontSize: 13,
      fontWeight: '600',
    },
    metricsContainer: {
      backgroundColor: theme.metricsBg,
      marginHorizontal: 16,
      marginTop: -12,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 16,
      flexDirection: 'row',
      justifyContent: 'space-around',
      borderWidth: 1,
      borderColor: theme.border,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
    },
    metricBox: {
      alignItems: 'center',
      flex: 1,
    },
    metricDivider: {
      width: 1,
      height: '80%',
      backgroundColor: theme.border,
      alignSelf: 'center',
    },
    metricVal: {
      fontSize: 17,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    metricLabel: {
      fontSize: 11,
      color: theme.textSecondary,
      fontWeight: '600',
      marginTop: 2,
    },
    daySelectorWrapper: {
      backgroundColor: theme.surface,
      marginTop: 12,
      borderBottomWidth: 1,
      borderColor: theme.border,
    },
    dayScrollContent: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      gap: 8,
    },
    dayTab: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: theme.tabBg,
      alignItems: 'center',
      minWidth: 64,
      borderWidth: 1,
      borderColor: theme.border,
    },
    dayTabActive: {
      backgroundColor: theme.tabActiveBg,
      borderColor: theme.tabActiveBg,
    },
    dayTabShort: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.tabText,
    },
    dayTabShortActive: {
      color: theme.tabActiveText,
    },
    dayTabFull: {
      fontSize: 10,
      color: theme.textMuted,
      marginTop: 1,
    },
    dayTabFullActive: {
      color: theme.tabActiveText,
    },
    streamContent: {
      padding: 16,
      paddingBottom: 90,
    },
    emptyCard: {
      padding: 40,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 40,
    },
    emptyIcon: {
      fontSize: 48,
      marginBottom: 12,
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.textPrimary,
      marginBottom: 6,
    },
    emptySub: {
      fontSize: 13,
      color: theme.textSecondary,
      textAlign: 'center',
      maxWidth: 280,
    },
    slotCard: {
      backgroundColor: theme.surface,
      borderRadius: 12,
      marginBottom: 14,
      flexDirection: 'row',
      borderWidth: 1,
      borderColor: theme.border,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 5,
    },
    slotCardCompleted: {
      opacity: 0.75,
      backgroundColor: theme.surfaceElevated,
    },
    slotTypeAccent: {
      width: 6,
    },
    slotBody: {
      flex: 1,
      padding: 16,
    },
    cardHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    typeBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    typeBadgeText: {
      fontSize: 11,
      fontWeight: '700',
    },
    timeSpanText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    subjectText: {
      fontSize: 17,
      fontWeight: '800',
      color: theme.textPrimary,
      marginBottom: 4,
    },
    topicText: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 12,
      lineHeight: 18,
    },
    cardFooterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    qTargetBadge: {
      backgroundColor: theme.surfaceElevated,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: theme.border,
    },
    qTargetText: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    actionBtnGroup: {
      flexDirection: 'row',
      gap: 8,
    },
    statusBtn: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 6,
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
    },
    completedActiveBtn: {
      backgroundColor: '#10B981',
      borderColor: '#10B981',
    },
    skippedActiveBtn: {
      backgroundColor: '#EF4444',
      borderColor: '#EF4444',
    },
    statusBtnText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    statusBtnTextActive: {
      color: '#FFFFFF',
    },
    fabTrigger: {
      position: 'absolute',
      bottom: 24,
      right: 20,
      backgroundColor: theme.primary,
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderRadius: 30,
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    fabIcon: {
      color: theme.primaryText,
      fontWeight: '700',
      fontSize: 14,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.75)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalCard: {
      backgroundColor: theme.surface,
      borderRadius: 16,
      padding: 24,
      width: '100%',
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalHeading: {
      fontSize: 19,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    modalSubheading: {
      fontSize: 13,
      color: theme.textSecondary,
      marginBottom: 16,
    },
    fieldLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textSecondary,
      marginBottom: 6,
      marginTop: 8,
    },
    textInput: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      padding: 10,
      fontSize: 14,
      color: theme.textPrimary,
      backgroundColor: theme.surfaceElevated,
    },
    typeSelectorRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginVertical: 4,
    },
    typeChoice: {
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceElevated,
    },
    typeChoiceActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    typeChoiceText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    typeChoiceTextActive: {
      color: theme.primaryText,
    },
    timeInputsRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 6,
    },
    inputCol: {
      flex: 1,
    },
    modalActionGroup: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 12,
      marginTop: 20,
    },
    abortBtn: {
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    abortBtnText: {
      color: theme.textMuted,
      fontWeight: '600',
    },
    confirmBtn: {
      backgroundColor: theme.primary,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
    },
    confirmBtnText: {
      color: theme.primaryText,
      fontWeight: '700',
    },
    themeListRow: {
      gap: 10,
      marginVertical: 12,
    },
    themeOptionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 14,
      borderRadius: 10,
      backgroundColor: theme.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.border,
    },
    themeOptionBtnActive: {
      borderColor: theme.primary,
      backgroundColor: theme.surface,
    },
    themeOptionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    themeOptionTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textPrimary,
    },
  });
}